name: Example

on:
  push:
    branches:
      - master

    tags:

  pull_request:

jobs:
  typescript:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          yarn install
      - name: Build
        run: |
          yarn workspace megalodon run build
      - name: Typescript example
        env:
          MASTODON_URL: https://fedibird.com
          PLEROMA_URL: https://pleroma.io
          FIREFISH_URL: https://cybre.club
          FRIENDICA_URL: https://squeet.me
        run: |
          yarn workspace example run build
          node example/typescript/dist/mastodon/instance.js
          node example/typescript/dist/pleroma/instance.js
          node example/typescript/dist/firefish/instance.js
          node example/typescript/dist/friendica/instance.js
  webpack:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          yarn install
      - name: Build
        run: |
          yarn workspace megalodon run build
      - name: Webpack example
        run: |
          yarn workspace webpack run build

  vite:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          yarn install
      - name: Build
        run: |
          yarn workspace megalodon run build
      - name: Vite example
        run: |
          yarn workspace vite build
