name: Example

on:
  push:
    branches:
      - master

    tags:

  pull_request:

jobs:
  node-cjs:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          yarn install
      - name: Build
        run: |
          yarn workspace megalodon run build
      - name: Node CJS example
        env:
          MASTODON_URL: https://fedibird.com
          PLEROMA_URL: https://pleroma.io
          FIREFISH_URL: https://cybre.club
          FRIENDICA_URL: https://squeet.me
        run: |
          yarn workspace node-cjs run build
          node example/node-cjs/dist/mastodon/instance.js
          node example/node-cjs/dist/pleroma/instance.js
          node example/node-cjs/dist/firefish/instance.js
          node example/node-cjs/dist/friendica/instance.js

  node-esm:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          yarn install
      - name: Build
        run: |
          yarn workspace megalodon run build
      - name: Node ESM example
        run: |
          yarn workspace node-esm run build

  webpack:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          yarn install
      - name: Build
        run: |
          yarn workspace megalodon run build
      - name: Webpack example
        run: |
          yarn workspace webpack run build

  vite:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          yarn install
      - name: Build
        run: |
          yarn workspace megalodon run build
      - name: Vite example
        run: |
          yarn workspace vite build
